/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema_Nutricao_Qualidade.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliana
 */
public class Tela_Principal extends javax.swing.JFrame {

    private int id_permissoes;

    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void validaPermissao(int id) {
        this.id_permissoes = id;

        if (id_permissoes == 1) { // Gerente Geral
            // Todas as permissões estão habilitadas, não precisa fazer nada

        } else if (id_permissoes == 2) { // Sócio
            jMenuItemCadDir.setVisible(false);
            // Todas as outras opções estão visíveis para o Sócio

        } else if (id_permissoes == 3) { // Nutricionista Supervisora
            jMenuItemCadUsuario.setVisible(false);
            jMenuItemCadDir.setVisible(false);
            jMenuItemCadFunc.setVisible(false);
            // Todas as outras opções estão visíveis para a Nutricionista Supervisora

        } else if (id_permissoes == 4) { // Nutricionista
            jMenuItemCadUsuario.setVisible(false);
            jMenuItemCadFunc.setVisible(false);
            jMenuItemCadDir.setVisible(false);
            jMenuItemCadCliente.setVisible(false);
            // Todas as outras opções estão visíveis para o Nutricionista
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelLogo = new javax.swing.JLabel();
        jLabelMensagen = new javax.swing.JLabel();
        jLabelQualinutri = new javax.swing.JLabel();
        jLabelImagemFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuItemCadUsuario = new javax.swing.JMenuItem();
        jMenuItemCadDir = new javax.swing.JMenuItem();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jMenuItemCadFunc = new javax.swing.JMenuItem();
        jMenuItemCadDoc = new javax.swing.JMenuItem();
        jMenuItemCadRel = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuItemConsUsuario = new javax.swing.JMenuItem();
        jMenuItemConsDiretoria = new javax.swing.JMenuItem();
        jMenuItemConsCliente = new javax.swing.JMenuItem();
        jMenuItemConsFuncionario = new javax.swing.JMenuItem();
        jMenuItemConsDocumento = new javax.swing.JMenuItem();
        jMenuItemConsRelatorio = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenu();
        jMenuItemListarUsu = new javax.swing.JMenuItem();
        jMenuItemListarCli = new javax.swing.JMenuItem();
        jMenuItemListarFunc = new javax.swing.JMenuItem();
        jMenuItemListarDoc = new javax.swing.JMenuItem();
        jMenuItemListarRel = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/puzzle.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 140, 140));

        jLabelMensagen.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabelMensagen.setForeground(new java.awt.Color(255, 153, 0));
        jLabelMensagen.setText("Empresa de Consultoria em Nutrição e Qualidade.");
        getContentPane().add(jLabelMensagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 590, -1));

        jLabelQualinutri.setFont(new java.awt.Font("Berlin Sans FB", 0, 120)); // NOI18N
        jLabelQualinutri.setForeground(new java.awt.Color(204, 51, 0));
        jLabelQualinutri.setText("QualiNutri ");
        getContentPane().add(jLabelQualinutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 580, 120));

        jLabelImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/unfinished-white-jigsaw med.jpg"))); // NOI18N
        getContentPane().add(jLabelImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/add.png"))); // NOI18N
        jMenuCadastrar.setText("Cadastrar");
        jMenuCadastrar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jMenuItemCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/add-user 24px .png"))); // NOI18N
        jMenuItemCadUsuario.setText("Cadastrar Novo Usuário");
        jMenuItemCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCadUsuario);

        jMenuItemCadDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/adddiretoria 24px.png"))); // NOI18N
        jMenuItemCadDir.setText("Cadastrar Diretoria");
        jMenuItemCadDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadDirActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCadDir);

        jMenuItemCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/add cliente 24px. png.png"))); // NOI18N
        jMenuItemCadCliente.setText("Cadastrar Cliente");
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCadCliente);

        jMenuItemCadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/add-func 24pxpng.png"))); // NOI18N
        jMenuItemCadFunc.setText("Cadastrar Funcionário");
        jMenuItemCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCadFunc);

        jMenuItemCadDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/new-document 24px.png"))); // NOI18N
        jMenuItemCadDoc.setText("Cadastrar Documento");
        jMenuItemCadDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadDocActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCadDoc);

        jMenuItemCadRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/Cad relatório 24pxpng.png"))); // NOI18N
        jMenuItemCadRel.setText("Cadastrar Relatório");
        jMenuItemCadRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadRelActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCadRel);

        jMenuBar1.add(jMenuCadastrar);

        jMenuConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/peaquisar2 32px.png"))); // NOI18N
        jMenuConsultar.setText("Consultar");
        jMenuConsultar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jMenuItemConsUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/user24px .png"))); // NOI18N
        jMenuItemConsUsuario.setText("Consultar Usuário");
        jMenuItemConsUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsUsuarioActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsUsuario);

        jMenuItemConsDiretoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/user24px.png"))); // NOI18N
        jMenuItemConsDiretoria.setText("Consultar Diretoria");
        jMenuConsultar.add(jMenuItemConsDiretoria);

        jMenuItemConsCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/search func 24px.png"))); // NOI18N
        jMenuItemConsCliente.setText("Consultar Cliente");
        jMenuItemConsCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsClienteActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsCliente);

        jMenuItemConsFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/search-user 24px.png"))); // NOI18N
        jMenuItemConsFuncionario.setText("Consultar Funcionário");
        jMenuItemConsFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsFuncionarioActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsFuncionario);

        jMenuItemConsDocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/search doc 24px.png"))); // NOI18N
        jMenuItemConsDocumento.setText("Consultar Documento");
        jMenuItemConsDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsDocumentoActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsDocumento);

        jMenuItemConsRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/cons relatorio 24pxpng.png"))); // NOI18N
        jMenuItemConsRelatorio.setText("Consultar Relatório");
        jMenuItemConsRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsRelatorioActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsRelatorio);

        jMenuBar1.add(jMenuConsultar);

        jMenuListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/Listar 4 32px.png"))); // NOI18N
        jMenuListar.setText("Listar");
        jMenuListar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jMenuItemListarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/client-profile 24px.png"))); // NOI18N
        jMenuItemListarUsu.setText("Listar Usuários");
        jMenuItemListarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarUsuActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemListarUsu);

        jMenuItemListarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/Cons dire 24pxpng.png"))); // NOI18N
        jMenuItemListarCli.setText("Listar Clientes");
        jMenuItemListarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarCliActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemListarCli);

        jMenuItemListarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/Listar func 24pxpng.png"))); // NOI18N
        jMenuItemListarFunc.setText("Listar Funcionários");
        jMenuItemListarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarFuncActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemListarFunc);

        jMenuItemListarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/lista docu 24px.png"))); // NOI18N
        jMenuItemListarDoc.setText("Listar Documentos");
        jMenuItemListarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarDocActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemListarDoc);

        jMenuItemListarRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/list relatorio 24px.png"))); // NOI18N
        jMenuItemListarRel.setText("Listar Relatórios");
        jMenuItemListarRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarRelActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemListarRel);

        jMenuBar1.add(jMenuListar);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/power-button32px.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/exit 24px.png"))); // NOI18N
        jMenuItemSair.setText("Sair do Sistema");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
        if (id_permissoes == 1 || id_permissoes == 2 || id_permissoes == 3) {
            TelaCad_Cliente cadcliente = new TelaCad_Cliente();
            cadcliente.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para cadastrar clientes.");
        }
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    private void jMenuItemCadDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadDocActionPerformed
        TelaCad_Documento caddocumentos = new TelaCad_Documento();
        caddocumentos.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadDocActionPerformed

    private void jMenuItemCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncActionPerformed
        if (id_permissoes == 1 || id_permissoes == 2) {
            TelaCad_Funcionario cadfuncionario = new TelaCad_Funcionario();
            cadfuncionario.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para cadastrar funcionários.");
        }
    }//GEN-LAST:event_jMenuItemCadFuncActionPerformed

    private void jMenuItemCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuarioActionPerformed
        if (id_permissoes == 1 || id_permissoes == 2) {
            TelaCad_Usuario cadusuario = new TelaCad_Usuario();
            cadusuario.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para cadastrar usuários.");
        }
    }//GEN-LAST:event_jMenuItemCadUsuarioActionPerformed

    private void jMenuItemCadDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadDirActionPerformed
        if (id_permissoes == 1) {
            TelaCad_Diretoria caddiretoria = new TelaCad_Diretoria();
            caddiretoria.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para cadastrar diretoria.");
        }
    }//GEN-LAST:event_jMenuItemCadDirActionPerformed

    private void jMenuItemCadRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadRelActionPerformed
        TelaCad_Relatorio cadrelatorios = new TelaCad_Relatorio();
        cadrelatorios.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadRelActionPerformed

    private void jMenuItemConsUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsUsuarioActionPerformed
        TelaCad_Usuario consCliente = new TelaCad_Usuario();
        consCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsUsuarioActionPerformed

    private void jMenuItemConsRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsRelatorioActionPerformed
        TelaCad_Relatorio consrelatorio = new TelaCad_Relatorio();
        consrelatorio.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsRelatorioActionPerformed

    private void jMenuItemConsFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsFuncionarioActionPerformed
        TelaCad_Funcionario consfunc = new TelaCad_Funcionario();
        consfunc.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsFuncionarioActionPerformed

    private void jMenuItemConsDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsDocumentoActionPerformed
        TelaLista_Doc consdoc = new TelaLista_Doc();
        consdoc.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsDocumentoActionPerformed

    private void jMenuItemConsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsClienteActionPerformed
        TelaCad_Cliente conscliente = new TelaCad_Cliente();
        conscliente.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsClienteActionPerformed

    private void jMenuItemListarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarUsuActionPerformed
        TelaLista_Usuario listausuario = new TelaLista_Usuario();
        listausuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarUsuActionPerformed

    private void jMenuItemListarRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarRelActionPerformed
        TelaLista_Relatorio listarelatorio = new TelaLista_Relatorio();
        listarelatorio.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarRelActionPerformed

    private void jMenuItemListarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarFuncActionPerformed
        TelaLista_Func listafunc = new TelaLista_Func();
        listafunc.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarFuncActionPerformed

    private void jMenuItemListarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarDocActionPerformed
        TelaLista_Doc listadoc = new TelaLista_Doc();
        listadoc.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarDocActionPerformed

    private void jMenuItemListarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarCliActionPerformed
        TelaLista_Cliente listacliente = new TelaLista_Cliente();
        listacliente.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarCliActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagemFundo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMensagen;
    private javax.swing.JLabel jLabelQualinutri;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemCadDir;
    private javax.swing.JMenuItem jMenuItemCadDoc;
    private javax.swing.JMenuItem jMenuItemCadFunc;
    private javax.swing.JMenuItem jMenuItemCadRel;
    private javax.swing.JMenuItem jMenuItemCadUsuario;
    private javax.swing.JMenuItem jMenuItemConsCliente;
    private javax.swing.JMenuItem jMenuItemConsDiretoria;
    private javax.swing.JMenuItem jMenuItemConsDocumento;
    private javax.swing.JMenuItem jMenuItemConsFuncionario;
    private javax.swing.JMenuItem jMenuItemConsRelatorio;
    private javax.swing.JMenuItem jMenuItemConsUsuario;
    private javax.swing.JMenuItem jMenuItemListarCli;
    private javax.swing.JMenuItem jMenuItemListarDoc;
    private javax.swing.JMenuItem jMenuItemListarFunc;
    private javax.swing.JMenuItem jMenuItemListarRel;
    private javax.swing.JMenuItem jMenuItemListarUsu;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuListar;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
