/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema_Nutricao_Qualidade.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import sistema_nutricao_qualidade.conexao.ConexaoDAO;
import sistema_nutricao_qualidade.controller.Cad_UsuarioDAO;
import sistema_nutricao_qualidade.model.Cadastro_Usuario;

/**
 *
 * @author Juliana
 */
public class TelaLista_Usuario extends javax.swing.JFrame {

   

    /**
     * Creates new form TelaLista_Usuario
     */
    public TelaLista_Usuario() {
        initComponents();
        
        this.preencherTabela("");
    }

    /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpar1 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaUsuarios = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtConsEmpresa = new javax.swing.JTextField();
        jlNomeDaEmpresa = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelMensagen = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(153, 0, 255));
        jButton9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/printing.png"))); // NOI18N
        jButton9.setText("Imprimir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(102, 102, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1, -1));

        btnLimpar1.setBackground(new java.awt.Color(102, 153, 255));
        btnLimpar1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpar1.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/limpar.png"))); // NOI18N
        btnLimpar1.setText("Limpar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, -1, -1));

        btnVoltar.setBackground(new java.awt.Color(255, 51, 0));
        btnVoltar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 51));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Lista de Usuários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(255, 102, 51))); // NOI18N
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        tblListaUsuarios.setBackground(new java.awt.Color(255, 153, 102));
        tblListaUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14), new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        tblListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Login", "Senha", "Tipo de Acesso", "Ultimo Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 950, 320));

        btnBuscar.setBackground(new java.awt.Color(102, 153, 255));
        btnBuscar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/log-in.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        txtConsEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        txtConsEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        txtConsEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(txtConsEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 300, -1));

        jlNomeDaEmpresa.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jlNomeDaEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        jlNomeDaEmpresa.setText("Login do Usuário:");
        getContentPane().add(jlNomeDaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/puzzle (1) 64px.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabelMensagen.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelMensagen.setForeground(new java.awt.Color(255, 153, 0));
        jLabelMensagen.setText("Empresa de Consultoria em Nutrição e Qualidade.");
        getContentPane().add(jLabelMensagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 300, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText("QualiNutri ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 70));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/borrao-abstrato-de-pastel-lindo-cor-de-rosa-pessego-ceu-tom-quente-fundo-para-design-como-bannerslid.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.preencherTabela(txtConsEmpresa.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtConsEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsEmpresaActionPerformed

    public void limparCampos() {
       
        txtConsEmpresa.setText("");
        txtConsEmpresa.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLista_Usuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLista_Usuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLista_Usuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLista_Usuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLista_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMensagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlNomeDaEmpresa;
    private javax.swing.JTable tblListaUsuarios;
    private javax.swing.JTextField txtConsEmpresa;
    // End of variables declaration//GEN-END:variables

    public void preencherTabela(String filtro) {

        Cad_UsuarioDAO usuariodao = new Cad_UsuarioDAO();
        ConexaoDAO dao = new ConexaoDAO();
        dao.conectar();

        if (dao == null) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        } else {

            List<Cadastro_Usuario> listaUsuarios = usuariodao.listar(filtro);
            DefaultTableModel tabelaUsuarios = (DefaultTableModel) tblListaUsuarios.getModel();
            tblListaUsuarios.setRowSorter(new TableRowSorter(tabelaUsuarios));
            tabelaUsuarios.setNumRows(0);

            for (Cadastro_Usuario cadUser : listaUsuarios) {

                Object[] obj = new Object[]{
                    cadUser.getId(),
                    cadUser.getLogin(),
                    cadUser.getConfirmar_Senha(),
                    cadUser.getTipoAcesso(),
                    cadUser.getUltimo_Login()

                };
                tabelaUsuarios.addRow(obj);

            }

            dao.desconectar();
        }
    }

}
