/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema_Nutricao_Qualidade.view;

/**
 *
 * @author Juliana
 */
public class TelaCad_ResponsáveisClientes extends javax.swing.JFrame {

    /**
     * Creates new form TelaCad_ResponsáveisClientes
     */
    public TelaCad_ResponsáveisClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtEmailSubGerente = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ftfCelSubGerente = new javax.swing.JFormattedTextField();
        jLabel33 = new javax.swing.JLabel();
        ftfTelSubGerente = new javax.swing.JFormattedTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtSobrenSubGerente = new javax.swing.JTextField();
        txtNomeSubGerente = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtEmailGerente = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        ftfCelGerente = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        ftfTelGerente = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtSobrenGerente = new javax.swing.JTextField();
        txtNomeGerente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        txtEmailRespLegal = new javax.swing.JTextField();
        ftfCelRespLegal = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        ftfTelefoneRespLegal = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSobrenomeRespLegal = new javax.swing.JTextField();
        txtNomeRespLegal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JlDadosResponsaveis = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelMensagen = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(255, 51, 0));
        jButton6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/back.png"))); // NOI18N
        jButton6.setText("Voltar");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jButton5.setText("Excluir");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, -1, -1));

        jButton4.setText("Cancelar");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, -1, -1));

        jButton3.setText("Limpar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, -1));

        jButton2.setText("Atualizar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jButton1.setText("Salvar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, -1));

        txtEmailSubGerente.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailSubGerente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtEmailSubGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 270, -1));

        jLabel29.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Email:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        ftfCelSubGerente.setBackground(new java.awt.Color(255, 255, 255));
        ftfCelSubGerente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ftfCelSubGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 140, -1));

        jLabel33.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Celular:");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, -1, -1));

        ftfTelSubGerente.setBackground(new java.awt.Color(255, 255, 255));
        ftfTelSubGerente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ftfTelSubGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 140, -1));

        jLabel32.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Telefone: ");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));

        jLabel31.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Sobrenome:");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        txtSobrenSubGerente.setBackground(new java.awt.Color(255, 255, 255));
        txtSobrenSubGerente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtSobrenSubGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 360, -1));

        txtNomeSubGerente.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeSubGerente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNomeSubGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 270, -1));

        jLabel30.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Nome Subgerente:");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 950, 20));

        txtEmailGerente.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailGerente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtEmailGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 280, -1));

        jLabel27.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Email:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        ftfCelGerente.setBackground(new java.awt.Color(255, 255, 255));
        ftfCelGerente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ftfCelGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 140, -1));

        jLabel26.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Celular:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, -1, -1));

        ftfTelGerente.setBackground(new java.awt.Color(255, 255, 255));
        ftfTelGerente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ftfTelGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 140, -1));

        jLabel25.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Telefone: ");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        jLabel24.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Sobrenome:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        txtSobrenGerente.setBackground(new java.awt.Color(255, 255, 255));
        txtSobrenGerente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtSobrenGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 360, -1));

        txtNomeGerente.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeGerente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNomeGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 280, -1));

        jLabel23.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Nome Gerente:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 950, -1));

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Email:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        txtEmailRespLegal.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailRespLegal.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailRespLegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailRespLegalActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmailRespLegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 280, -1));

        ftfCelRespLegal.setBackground(new java.awt.Color(255, 255, 255));
        ftfCelRespLegal.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ftfCelRespLegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 150, -1));

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Celular:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        ftfTelefoneRespLegal.setBackground(new java.awt.Color(255, 255, 255));
        ftfTelefoneRespLegal.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ftfTelefoneRespLegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 140, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Telefone: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Sobrenome:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        txtSobrenomeRespLegal.setBackground(new java.awt.Color(255, 255, 255));
        txtSobrenomeRespLegal.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtSobrenomeRespLegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 360, -1));

        txtNomeRespLegal.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeRespLegal.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNomeRespLegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 220, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nome Responsável Legal:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        JlDadosResponsaveis.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        JlDadosResponsaveis.setForeground(new java.awt.Color(255, 102, 51));
        JlDadosResponsaveis.setText("Dados Responsáveis");
        getContentPane().add(JlDadosResponsaveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CADASTRAR CLIENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(383, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(350, 350, 350))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 950, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/puzzle (1) 64px.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabelMensagen.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelMensagen.setForeground(new java.awt.Color(255, 153, 0));
        jLabelMensagen.setText("Empresa de Consultoria em Nutrição e Qualidade.");
        getContentPane().add(jLabelMensagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 300, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText("QualiNutri ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 70));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/borrao-abstrato-de-pastel-lindo-cor-de-rosa-pessego-ceu-tom-quente-fundo-para-design-como-bannerslid.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailRespLegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailRespLegalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailRespLegalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCad_ResponsáveisClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCad_ResponsáveisClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCad_ResponsáveisClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCad_ResponsáveisClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCad_ResponsáveisClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlDadosResponsaveis;
    private javax.swing.JFormattedTextField ftfCelGerente;
    private javax.swing.JFormattedTextField ftfCelRespLegal;
    private javax.swing.JFormattedTextField ftfCelSubGerente;
    private javax.swing.JFormattedTextField ftfTelGerente;
    private javax.swing.JFormattedTextField ftfTelSubGerente;
    private javax.swing.JFormattedTextField ftfTelefoneRespLegal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMensagen;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtEmailGerente;
    private javax.swing.JTextField txtEmailRespLegal;
    private javax.swing.JTextField txtEmailSubGerente;
    private javax.swing.JTextField txtNomeGerente;
    private javax.swing.JTextField txtNomeRespLegal;
    private javax.swing.JTextField txtNomeSubGerente;
    private javax.swing.JTextField txtSobrenGerente;
    private javax.swing.JTextField txtSobrenSubGerente;
    private javax.swing.JTextField txtSobrenomeRespLegal;
    // End of variables declaration//GEN-END:variables
}
