/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema_Nutricao_Qualidade.view;

import java.sql.Connection;
import javax.swing.JOptionPane;
import sistema_nutricao_qualidade.conexao.ConexaoDAO;
import sistema_nutricao_qualidade.controller.Cad_UsuarioDAO;
import sistema_nutricao_qualidade.model.Cadastro_Usuario;
import java.sql.SQLException;

/**
 *
 * @author Juliana
 */
public class TelaCad_Usuario extends javax.swing.JFrame {

    private TelaLista_Usuario telaLista;

    public TelaCad_Usuario() {
        initComponents();
    }

    public TelaCad_Usuario(TelaLista_Usuario telaLista) {
        this.telaLista = telaLista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabelMensagen = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        ftfSenha = new javax.swing.JPasswordField();
        btnExcluir = new javax.swing.JButton();
        ftfConfirmarSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnPaginaInicial = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        txtConsId = new javax.swing.JTextField();
        jcbTipoDeAcesso = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText("QualiNutri ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, 70));

        jLabelMensagen.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelMensagen.setForeground(new java.awt.Color(255, 153, 0));
        jLabelMensagen.setText("Empresa de Consultoria em Nutrição e Qualidade.");
        getContentPane().add(jLabelMensagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 300, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/puzzle (1) 64px.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        btnListar.setBackground(new java.awt.Color(0, 0, 255));
        btnListar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/listar.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 120, -1));

        btnSalvar.setBackground(new java.awt.Color(0, 204, 0));
        btnSalvar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/save-file.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 130, 50));

        ftfSenha.setBackground(new java.awt.Color(255, 255, 255));
        ftfSenha.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ftfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 260, 40));

        btnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluir.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, -1, 50));

        ftfConfirmarSenha.setBackground(new java.awt.Color(255, 255, 255));
        ftfConfirmarSenha.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(ftfConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 280, 40));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CADASTRAR DE USUÁRIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(408, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(353, 353, 353))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1000, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(102, 102, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, -1, 50));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Login:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Confirmação de senha: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        btnLimpar.setBackground(new java.awt.Color(102, 153, 255));
        btnLimpar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, -1, 50));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        btnPaginaInicial.setBackground(new java.awt.Color(153, 153, 153));
        btnPaginaInicial.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPaginaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/home 1 32px.png"))); // NOI18N
        btnPaginaInicial.setText("Página Inicial");
        btnPaginaInicial.setToolTipText("Voltar para Página Inicial");
        btnPaginaInicial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnPaginaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaInicialActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaginaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 150, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo de acesso:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        btnPesquisar.setBackground(new java.awt.Color(102, 153, 255));
        btnPesquisar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/buscar 32px.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        txtLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtLogin.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 280, 40));

        txtConsId.setBackground(new java.awt.Color(255, 255, 255));
        txtConsId.setForeground(new java.awt.Color(0, 0, 0));
        txtConsId.setToolTipText("Informe o número do ID do Usuário que deseja consultar.");
        getContentPane().add(txtConsId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 98, 80, 40));

        jcbTipoDeAcesso.setBackground(new java.awt.Color(255, 102, 51));
        jcbTipoDeAcesso.setForeground(new java.awt.Color(0, 0, 0));
        jcbTipoDeAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Gerente Geral", "Sócio Administrativo", "Nutricionista Supervisor (a)", "Nutricionista", " ", " " }));
        getContentPane().add(jcbTipoDeAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 260, 40));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ID:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btnAtualizar.setBackground(new java.awt.Color(102, 153, 255));
        btnAtualizar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/Atualizar arquivo.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, 50));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/borrao-abstrato-de-pastel-lindo-cor-de-rosa-pessego-ceu-tom-quente-fundo-para-design-como-bannerslid.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        TelaLista_Usuario telaLista = new TelaLista_Usuario();
        telaLista.setVisible(true);

        String filtro = "";
        telaLista.preencherTabela(filtro);

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        String login = txtLogin.getText();
        String senha = String.valueOf(ftfSenha.getPassword());
        String confsenha = String.valueOf(ftfConfirmarSenha.getPassword());
        String acesso = jcbTipoDeAcesso.getSelectedItem().toString();

        if (login.isEmpty() || senha.isEmpty() || confsenha.isEmpty() || acesso.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos inválidos ou não preenchidos");

        } else if (!senha.equals(confsenha)) {//verifica se a senha é diferente  da conformação da senha.
            JOptionPane.showMessageDialog(null, "A confirmação de senha não coincide com a senha digitada");

        } else {
            int id_permissoes = 0;

            if (acesso.equals("Gerente Geral")) {
                id_permissoes = 1;
            } else if (acesso.equals("Sócio Administrativo")) {
                id_permissoes = 2;
            } else if (acesso.equals("Nutricionista Supervisor(a)")) {
                id_permissoes = 3;
            } else if (acesso.equals("Nutricionista")) {
                id_permissoes = 4;
            }

            Cadastro_Usuario cadUsuario = new Cadastro_Usuario();
            cadUsuario.setLogin(login);
            cadUsuario.setSenha(senha);
            cadUsuario.setConfirmar_Senha(confsenha);
            cadUsuario.setTipoAcesso(acesso);
            cadUsuario.setId_permissoes(id_permissoes);

            Cad_UsuarioDAO usuariodao = new Cad_UsuarioDAO();
            usuariodao.salvar(cadUsuario);

            JOptionPane.showMessageDialog(null, "Dados incluidos com sucesso");

            limparCampos();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Cadastro_Usuario cadUsuario = new Cadastro_Usuario();
        Cad_UsuarioDAO usuarioDao = new Cad_UsuarioDAO();

        ConexaoDAO conDAO = new ConexaoDAO();
        Connection conn = conDAO.conectar();

        if (conn != null) {
            int idUsuario = Integer.parseInt(txtConsId.getText());

            boolean excluir = usuarioDao.excluir(idUsuario);

            if (excluir) {
                JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso!");
                this.limparCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Erro na exclusão do Usuário!");
            }
            conDAO.desconectar();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPaginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaInicialActionPerformed
        Tela_Principal telaprinc = new Tela_Principal();
        telaprinc.setVisible(true);
    }//GEN-LAST:event_btnPaginaInicialActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        int idPesquisa = Integer.parseInt(txtConsId.getText());

        Cad_UsuarioDAO usuariodao = new Cad_UsuarioDAO();
        Cadastro_Usuario cadUsuario = usuariodao.consultar(idPesquisa);

        if (cadUsuario == null) {
            JOptionPane.showMessageDialog(this, "Usuário não encontrado!");
        } else {
            txtLogin.setText(cadUsuario.getLogin());
            ftfSenha.setText(cadUsuario.getSenha());
            ftfConfirmarSenha.setText(cadUsuario.getConfirmar_Senha());
            jcbTipoDeAcesso.setSelectedItem(cadUsuario.getTipoAcesso());
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        Cadastro_Usuario cadUsuario = new Cadastro_Usuario();
        Cad_UsuarioDAO usuarioDao = new Cad_UsuarioDAO();

        int idUsuario = Integer.parseInt(txtConsId.getText());
        String login = txtLogin.getText();
        String senha = String.valueOf(ftfSenha.getPassword());
        String confsenha = String.valueOf(ftfConfirmarSenha.getPassword());
        String acesso = jcbTipoDeAcesso.getSelectedItem().toString();

        cadUsuario.setId(idUsuario);
        cadUsuario.setLogin(login);
        cadUsuario.setSenha(senha);
        cadUsuario.setConfirmar_Senha(confsenha);
        cadUsuario.setTipoAcesso(acesso);

        ConexaoDAO conDAO = new ConexaoDAO();
        Connection conn = conDAO.conectar();

        if (conn != null) {

            int resposta = usuarioDao.atualizar(cadUsuario);
            System.out.println(cadUsuario.getId());

            if (resposta == 1) {
                JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso");
                this.limparCampos();

            } else if (resposta == 1062) {
                JOptionPane.showMessageDialog(null, "Usuário já cadastrado");

            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar atualizar Usuário");
            }
            conDAO.desconectar();
        }

        limparCampos();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    public void limparCampos() {
        txtConsId.setText("");
        txtLogin.setText("");
        ftfSenha.setText("");
        ftfConfirmarSenha.setText("");
        txtLogin.requestFocus();
    }

    public void preencherCampos(Cadastro_Usuario cadUsuario) {
        txtLogin.setText(cadUsuario.getLogin());
        ftfSenha.setText(cadUsuario.getSenha());
        jcbTipoDeAcesso.setSelectedItem(cadUsuario.getTipoAcesso());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCad_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPaginaInicial;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPasswordField ftfConfirmarSenha;
    private javax.swing.JPasswordField ftfSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMensagen;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbTipoDeAcesso;
    private javax.swing.JTextField txtConsId;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
