/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema_Nutricao_Qualidade.view;

/**
 *
 * @author Juliana
 */
public class TelaLista_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaLista_Cliente
     */
    public TelaLista_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaClientes = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        txtConsCliente = new javax.swing.JTextField();
        jlNomeDaEmpresa = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelMensagen = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(255, 51, 0));
        jButton6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/back.png"))); // NOI18N
        jButton6.setText("Voltar");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), new java.awt.Color(255, 102, 51)), "Lista de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(255, 102, 51))); // NOI18N
        jScrollPane1.setToolTipText("");

        tblListaClientes.setBackground(new java.awt.Color(255, 255, 102));
        tblListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome da Empresa", "CNPJ", "Razão Social", "Email", "Telefone", "Rua", "Nº", "CEP", "Bairro", "Cidade", "Estado", "Complemento", "Responsável legal", "Sobrenome", "Telefone", "Celular", "Email", "Nome Gerente", "Sobrenome", "Telefone", "Celular", "Email", "Nome Subgerente", "Sobrenome", "Telefone", "Celular", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1000, 330));

        btnConsultar.setBackground(new java.awt.Color(102, 153, 255));
        btnConsultar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Buscar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        txtConsCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtConsCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtConsCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtConsCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 320, -1));

        jlNomeDaEmpresa.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jlNomeDaEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        jlNomeDaEmpresa.setText("Nome da Empresa:");
        getContentPane().add(jlNomeDaEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/puzzle (1) 64px.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabelMensagen.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelMensagen.setForeground(new java.awt.Color(255, 153, 0));
        jLabelMensagen.setText("Empresa de Consultoria em Nutrição e Qualidade.");
        getContentPane().add(jLabelMensagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 300, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText("QualiNutri ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 70));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/borrao-abstrato-de-pastel-lindo-cor-de-rosa-pessego-ceu-tom-quente-fundo-para-design-como-bannerslid.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        this.preencherTabela(txtConsCliente.getText());
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtConsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsClienteActionPerformed
    public void preencherTabela(String filtro) {

        /*  ClientesDAO cliDao = new ClientesDAO();
        ConexaoDAO dao = new ConexaoDAO();
        dao.conectar();

        if (dao == null) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        } else {

            List<Clientes> listaClientes = cliDao.listar(filtro);
            DefaultTableModel tabelaClientes = (DefaultTableModel) tblListaClientes.getModel();
            tblListaClientes.setRowSorter(new TableRowSorter(tabelaClientes));
            tabelaClientes.setNumRows(0);

            for (Clientes cli : listaClientes) {

                Object[] obj = new Object[]{
                    cli.getId(),
                    cli.getNome_Fantasia(),
                    cli.getCnpj(),
                    cli.getRazao_Social(),
                    cli.getEmail(),
                    cli.getTelefone(),
                    cli.getEndereco().getRua(),
                    cli.getEndereco().getNumero(),
                    cli.getEndereco().getCep(),
                    cli.getEndereco().getBairro(),
                    cli.getEndereco().getCidade(),
                    cli.getEndereco().getEstado(),
                    cli.getEndereco().getComplemento(),
                    cli.getNome(),
                    cli.getSobrenome(),
                    cli.getTelefone(),
                    cli.getCelular(),
                    cli.getEmail(),
                    cli.getNome(),
                    cli.getSobrenome(),
                    cli.getTelefone(),
                    cli.getCelular(),
                    cli.getEmail(),
                    cli.getNome(),
                    cli.getSobrenome(),
                    cli.getTelefone(),
                    cli.getCelular(),
                    cli.getEmail(),};
                tabelaClientes.addRow(obj);

            }

            dao.desconectar();
        }*/
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLista_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLista_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMensagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlNomeDaEmpresa;
    private javax.swing.JTable tblListaClientes;
    private javax.swing.JTextField txtConsCliente;
    // End of variables declaration//GEN-END:variables
}
