/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema_Nutricao_Qualidade.view;

import Sistema_Nutricao_Qualidade.view.Tela_Principal;
import javax.swing.JOptionPane;
import sistema_nutricao_qualidade.controller.Cad_UsuarioDAO;
import sistema_nutricao_qualidade.model.Cadastro_Usuario;

/**
 *
 * @author Juliana
 */
public class Tela_Login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Login
     */
    private Tela_Principal telaPrincipal;

    public Tela_Login(Tela_Principal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadeado = new javax.swing.JLabel();
        txtCadeado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBonecoUser = new javax.swing.JTextField();
        jLabelEntrar = new javax.swing.JLabel();
        jLabelOlho = new javax.swing.JLabel();
        btnCadNovoUsuario = new javax.swing.JButton();
        jLabelboneco = new javax.swing.JLabel();
        jblEsqueceuSenha = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jpfSenha = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelMensagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCadeado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/padlock 32px.png"))); // NOI18N
        getContentPane().add(jLabelCadeado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        txtCadeado.setEditable(false);
        txtCadeado.setBackground(new java.awt.Color(255, 255, 255));
        txtCadeado.setForeground(new java.awt.Color(0, 0, 0));
        txtCadeado.setToolTipText("Nome de usuário.");
        getContentPane().add(txtCadeado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/user 32px.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        txtBonecoUser.setEditable(false);
        txtBonecoUser.setBackground(new java.awt.Color(255, 255, 255));
        txtBonecoUser.setForeground(new java.awt.Color(0, 0, 0));
        txtBonecoUser.setToolTipText("Nome de usuário.");
        getContentPane().add(txtBonecoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 50, 50));

        jLabelEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/Entrar32px.png"))); // NOI18N
        getContentPane().add(jLabelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, -1, -1));

        jLabelOlho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/hidden.png"))); // NOI18N
        getContentPane().add(jLabelOlho, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, -1, -1));

        btnCadNovoUsuario.setBackground(new java.awt.Color(102, 255, 255));
        btnCadNovoUsuario.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnCadNovoUsuario.setForeground(new java.awt.Color(0, 153, 255));
        btnCadNovoUsuario.setText("Novo Login");
        btnCadNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadNovoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadNovoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 170, 50));

        jLabelboneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/user128px.png"))); // NOI18N
        getContentPane().add(jLabelboneco, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 140, 140));

        jblEsqueceuSenha.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jblEsqueceuSenha.setForeground(new java.awt.Color(0, 0, 0));
        jblEsqueceuSenha.setText("Esqueceu o seu login ou senha?");
        getContentPane().add(jblEsqueceuSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 177, -1));

        btnEntrar.setBackground(new java.awt.Color(255, 102, 0));
        btnEntrar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("Entrar");
        btnEntrar.setToolTipText("Fazer Login.");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 170, 50));

        jpfSenha.setBackground(new java.awt.Color(255, 255, 255));
        jpfSenha.setForeground(new java.awt.Color(0, 0, 0));
        jpfSenha.setToolTipText("Senha.");
        getContentPane().add(jpfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 350, 50));

        txtLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtLogin.setForeground(new java.awt.Color(0, 0, 0));
        txtLogin.setToolTipText("Nome de usuário.");
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 350, 50));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Senha:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 58, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Login:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 58, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 984, -1));

        jLabelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/15186101_5578724.jpg"))); // NOI18N
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 540, 340));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/puzzle (1) 64px.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabelMensagen.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelMensagen.setForeground(new java.awt.Color(255, 153, 0));
        jLabelMensagen.setText("Empresa de Consultoria em Nutrição e Qualidade.");
        getContentPane().add(jLabelMensagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 300, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("QualiNutri ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, 70));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/white-puzzle.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String nome = txtLogin.getText();
        String senha = String.valueOf(jpfSenha.getPassword());

        int id_permissoes = 0;
        String permissao = "";
        String nome_login = "";

        if (nome.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos inválidos ou não preenchidos");

        } else {

            Cad_UsuarioDAO user = new Cad_UsuarioDAO();
            Cadastro_Usuario userEncontrado = user.validarLogin(nome, senha);

            if (userEncontrado == null) {
                JOptionPane.showMessageDialog(null, "Login ou senha incorretos. Por favor, tente novamente.");
            } else {
                id_permissoes = userEncontrado.getId_permissoes();
                nome_login = userEncontrado.getLogin();

                if (id_permissoes == 1) {
                    permissao = "Gerente";
                } else if (id_permissoes == 2) {
                    permissao = "Administrador";
                } else if (id_permissoes == 3) {
                    permissao = "Nutricionista Supervisor(a)";
                } else if (id_permissoes == 4) {
                    permissao = "Nutricionista";
                }

                JOptionPane.showMessageDialog(null, "Olá " + nome_login + ". Sua permissão é do tipo " + permissao);
                dispose();

                Tela_Principal telaPrincipal = this.telaPrincipal;
                telaPrincipal.validaPermissao(id_permissoes);
                telaPrincipal.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnCadNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadNovoUsuarioActionPerformed
        TelaCad_Usuario cadlogin = new TelaCad_Usuario();
        cadlogin.setVisible(true);
    }//GEN-LAST:event_btnCadNovoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tela_Login telaLogin = new Tela_Login(new Tela_Principal());
                telaLogin.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadNovoUsuario;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCadeado;
    private javax.swing.JLabel jLabelEntrar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMensagen;
    private javax.swing.JLabel jLabelOlho;
    private javax.swing.JLabel jLabelboneco;
    private javax.swing.JLabel jblEsqueceuSenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField txtBonecoUser;
    private javax.swing.JTextField txtCadeado;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
