/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema_Nutricao_Qualidade.view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import sistema_nutricao_qualidade.conexao.ConexaoDAO;
import java.sql.Connection;
import sistema_nutricao_qualidade.controller.Cad_UsuarioDAO;
import sistema_nutricao_qualidade.controller.FuncionarioDAO;
import sistema_nutricao_qualidade.model.Cadastro_Usuario;
import sistema_nutricao_qualidade.model.Endereco;
import sistema_nutricao_qualidade.model.Funcionario;

/**
 *
 * @author Juliana
 */
public class TelaCad_Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCad_Funcionario
     */
    public TelaCad_Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtComplemento = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ftfCep = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ftfCpf = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        ftfCelular = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ftfCrn = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        ftfRg = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        ftfTelefone = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        ftfDataNasc = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtConsId = new javax.swing.JTextField();
        btnPesquisaId = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnPaginaInicial = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelMensagen = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluir.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(102, 102, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, -1, -1));

        btnLimpar.setBackground(new java.awt.Color(102, 153, 255));
        btnLimpar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, -1, -1));

        btnAtualizar.setBackground(new java.awt.Color(102, 153, 255));
        btnAtualizar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/Atualizar arquivo.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(0, 204, 0));
        btnSalvar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/save-file.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, -1, -1));

        txtComplemento.setBackground(new java.awt.Color(255, 255, 255));
        txtComplemento.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 240, -1));

        jLabel23.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Complemento:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, -1, -1));

        txtEstado.setBackground(new java.awt.Color(255, 255, 255));
        txtEstado.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 40, 30));

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Estado:*");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, -1, -1));

        txtCidade.setBackground(new java.awt.Color(255, 255, 255));
        txtCidade.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 160, -1));

        jLabel19.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Cidade:*");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        ftfCep.setBackground(new java.awt.Color(255, 255, 255));
        ftfCep.setForeground(new java.awt.Color(0, 0, 0));
        try {
            ftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 170, -1));

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("CEP:*");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        txtBairro.setBackground(new java.awt.Color(255, 255, 255));
        txtBairro.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 330, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Bairro:*");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        txtNumero.setBackground(new java.awt.Color(255, 255, 255));
        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 130, -1));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nº:*");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        txtRua.setBackground(new java.awt.Color(255, 255, 255));
        txtRua.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 280, -1));

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Rua:*");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 51, 0));
        jLabel14.setText("Dados Endereço");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 990, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 990, 30));

        txtIdUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 60, 30));

        jLabel13.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ID Usuário:*");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        ftfCpf.setBackground(new java.awt.Color(255, 255, 255));
        ftfCpf.setForeground(new java.awt.Color(0, 0, 0));
        try {
            ftfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftfCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 250, 30));

        jLabel12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("CPF:*");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, -1));

        ftfCelular.setBackground(new java.awt.Color(255, 255, 255));
        ftfCelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            ftfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftfCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 250, 30));

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Celular:*");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 260, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Email:*");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        txtSobrenome.setBackground(new java.awt.Color(255, 255, 255));
        txtSobrenome.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 350, 30));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sobrenome:*");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*Campos obrigatórios.");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, -1, 20));

        ftfCrn.setBackground(new java.awt.Color(255, 255, 255));
        ftfCrn.setForeground(new java.awt.Color(0, 0, 0));
        try {
            ftfCrn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftfCrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 210, 30));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("CRN:*");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        ftfRg.setBackground(new java.awt.Color(255, 255, 255));
        ftfRg.setForeground(new java.awt.Color(0, 0, 0));
        try {
            ftfRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftfRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 210, 30));

        jLabel24.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("RG:*");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        ftfTelefone.setBackground(new java.awt.Color(255, 255, 255));
        ftfTelefone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            ftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 170, 30));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Telefone Residencial:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        ftfDataNasc.setBackground(new java.awt.Color(255, 255, 255));
        ftfDataNasc.setForeground(new java.awt.Color(0, 0, 0));
        try {
            ftfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(ftfDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 200, 30));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Data de Nasc.:*");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 240, 30));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome:*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, 20));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("Dados Pessoais");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CADASTRAR FUNCIONÁRIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(343, 343, 343))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1000, -1));

        jLabel35.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("ID Usuário:");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtConsId.setBackground(new java.awt.Color(255, 255, 255));
        txtConsId.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtConsId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 70, 40));

        btnPesquisaId.setBackground(new java.awt.Color(102, 153, 255));
        btnPesquisaId.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPesquisaId.setForeground(new java.awt.Color(0, 0, 0));
        btnPesquisaId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/buscar 32px.png"))); // NOI18N
        btnPesquisaId.setText("Pesquisar");
        btnPesquisaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaIdActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        btnListar.setBackground(new java.awt.Color(0, 0, 255));
        btnListar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/listar.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 90, 110, -1));

        btnPaginaInicial.setBackground(new java.awt.Color(204, 204, 204));
        btnPaginaInicial.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPaginaInicial.setForeground(new java.awt.Color(153, 153, 153));
        btnPaginaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/views/icones/home 1 32px.png"))); // NOI18N
        btnPaginaInicial.setText("Página Inicial");
        btnPaginaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaInicialActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaginaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/puzzle (1) 64px.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabelMensagen.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelMensagen.setForeground(new java.awt.Color(255, 153, 0));
        jLabelMensagen.setText("Empresa de Consultoria em Nutrição e Qualidade.");
        getContentPane().add(jLabelMensagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 300, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setText("QualiNutri ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, 70));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema_Nutricao_Qualidade/view/imagens/borrao-abstrato-de-pastel-lindo-cor-de-rosa-pessego-ceu-tom-quente-fundo-para-design-como-bannerslid.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaInicialActionPerformed
        Tela_Principal telaprinc = new Tela_Principal();
        telaprinc.setVisible(true);
    }//GEN-LAST:event_btnPaginaInicialActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        TelaLista_Func telaListaFunc = new TelaLista_Func();
        telaListaFunc.setVisible(true);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnPesquisaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaIdActionPerformed
        int idPesquisa = Integer.parseInt(txtConsId.getText());

        FuncionarioDAO funcdao = new FuncionarioDAO();
        Funcionario func = funcdao.consultar(idPesquisa);

        if (func == null) {
            JOptionPane.showMessageDialog(this, "ID funcionário não encontrado!");
        } else {
            txtNome.setText(func.getNome());
            txtSobrenome.setText(func.getSobrenome());
            ftfDataNasc.setText(reverterData(String.valueOf(func.getData_Nascimento())));
            ftfRg.setText(func.getRg());
            ftfCpf.setText(func.getCpf());
            ftfTelefone.setText(func.getTelefone());
            txtEmail.setText(func.getEmail());
            ftfCelular.setText(func.getCelular());
            ftfCrn.setText(func.getCrn());

            Cadastro_Usuario usuario = func.getUsuario();

            if (usuario != null) {
                txtIdUsuario.setText(String.valueOf(usuario.getId()));
            } else {
                txtIdUsuario.setText("");
            }
            Endereco end = func.getEndereco();
            if (end != null) {
                txtRua.setText(end.getRua());
                txtNumero.setText(String.valueOf(end.getNumero()));
                txtBairro.setText(end.getBairro());
                ftfCep.setText(end.getCep());
                txtCidade.setText(end.getCidade());
                txtEstado.setText(end.getEstado());
                txtComplemento.setText(end.getComplemento());
            }
        }

    }//GEN-LAST:event_btnPesquisaIdActionPerformed

    private void txtIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Funcionario funcionario = new Funcionario();

        String nome = txtNome.getText();
        String sobrenome = txtSobrenome.getText();
        String email = txtEmail.getText();
        String telefone = ftfTelefone.getText();
        String celular = ftfCelular.getText();
        String rg = ftfRg.getText();
        String cpf = ftfCpf.getText();
        String crn = ftfCrn.getText();
        String rua = txtRua.getText();
        int numero = Integer.parseInt(txtNumero.getText());
        String cep = ftfCep.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();
        String complemento = txtComplemento.getText();

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date dataNascimento = null;
        try {
            dataNascimento = dateFormat.parse(ftfDataNasc.getText());
        } catch (ParseException ex) {
            System.out.println("Erro na conversão da data.");
            return;
        }

        if (emptyFields()) {// ver se não é (!emptyFields()) 
            return;
        }

        if (strValidacao()) {// ver se não é (!strValidacao())
            return;
        }
        int usuarioId = Integer.parseInt(txtIdUsuario.getText());
        Cad_UsuarioDAO usuarioDao = new Cad_UsuarioDAO();
        Cadastro_Usuario usuario = usuarioDao.buscarPorId(usuarioId);
        if (usuario == null) {
            JOptionPane.showMessageDialog(null, "Id do usuário não encontrado");
        } else {
            funcionario.setUsuario(usuario);
        }

        funcionario.setUsuario(usuario);

        funcionario.setNome(nome);
        funcionario.setSobrenome(sobrenome);
        funcionario.setData_Nascimento(dataNascimento);
        funcionario.setEmail(email);
        funcionario.setTelefone(telefone);
        funcionario.setCelular(celular);
        funcionario.setRg(rg);
        funcionario.setCpf(cpf);
        funcionario.setCrn(crn);

        Endereco endereco = new Endereco();
        endereco.setRua(rua);
        endereco.setNumero(numero);
        endereco.setCep(cep);
        endereco.setBairro(bairro);
        endereco.setCidade(cidade);
        endereco.setEstado(estado);
        endereco.setComplemento(complemento);

        funcionario.setEndereco(endereco);

        FuncionarioDAO funcionarioDao = new FuncionarioDAO();
        int status = funcionarioDao.salvar(funcionario);

        if (status == 1) {
            JOptionPane.showMessageDialog(null, "Dados incluídos com sucesso");
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao salvar dados do funcionário");
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        Funcionario func = new Funcionario();
        FuncionarioDAO funcdao = new FuncionarioDAO();

        int id = Integer.parseInt(txtConsId.getText());
        String nome = txtNome.getText();
        String sobrenome = txtSobrenome.getText();
        String rg = ftfRg.getText();
        String cpf = ftfCpf.getText();
        String telefone = ftfTelefone.getText();
        String email = txtEmail.getText();
        String celular = ftfCelular.getText();
        String crn = ftfCrn.getText();
        String rua = txtRua.getText();
        int numero = Integer.parseInt(txtNumero.getText());
        String cep = ftfCep.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();
        String complemento = txtComplemento.getText();

        String dataRecebida = ftfDataNasc.getText();
        SimpleDateFormat conversor = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Date dataConvertida = conversor.parse(dataRecebida);
            java.sql.Date sqlDate = new java.sql.Date(dataConvertida.getTime());
            func.setData_Nascimento(sqlDate);

        } catch (ParseException ex) {
            System.out.println("Erro na conversão da data.");
        }

        ConexaoDAO conDAO = new ConexaoDAO();
        Connection conn = conDAO.conectar();

        if (conn != null) {

            func.setId(id);
            func.setNome(nome);
            func.setSobrenome(sobrenome);
            func.setRg(rg);
            func.setCpf(cpf);
            func.setTelefone(telefone);
            func.setEmail(email);
            func.setCelular(celular);
            func.setCrn(crn);

            Endereco end = new Endereco();
            end.setRua(rua);
            end.setNumero(numero);
            end.setCep(cep);
            end.setBairro(bairro);
            end.setCidade(cidade);
            end.setEstado(estado);
            end.setComplemento(complemento);

            func.setEndereco(end);

            int usuarioId = Integer.parseInt(txtIdUsuario.getText());
            Cad_UsuarioDAO usuarioDao = new Cad_UsuarioDAO();
            Cadastro_Usuario usuario = usuarioDao.buscarPorId(usuarioId);

            if (usuario == null) {
                JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
                return;
            } else {
                func.setUsuario(usuario);
            }

            int resposta = funcdao.atualizar(func);
            //System.out.println(func.getId());

            if (resposta == 1) {

                JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso");
                this.limparCampos();

            } else if (resposta == 1062) {
                JOptionPane.showMessageDialog(null, "Funcionário já foi cadastrado");

            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar atualizar dados");
            }
            conDAO.desconectar();
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id = Integer.parseInt(txtConsId.getText());
        ConexaoDAO conDao = new ConexaoDAO();
        FuncionarioDAO funcDao = new FuncionarioDAO();
        funcDao.excluir(id);

        if (funcDao == null) {
            JOptionPane.showMessageDialog(null, "Erro na exclusão!");
        } else {
            JOptionPane.showMessageDialog(null, "Funcionário excluído com sucesso!");
            this.limparCampos();
        }
        conDao.desconectar();
    }//GEN-LAST:event_btnExcluirActionPerformed

    public void limparCampos() {
        txtConsId.setText("");
        txtNome.setText("");
        txtSobrenome.setText("");
        ftfDataNasc.setText("");
        ftfRg.setText("");
        ftfCpf.setText("");
        ftfTelefone.setText("");
        txtEmail.setText("");
        ftfCelular.setText("");
        ftfCrn.setText("");
        txtIdUsuario.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        ftfCep.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtComplemento.setText("");
        txtNome.requestFocus();
    }

    public String reverterData(String data) {

        String dia = data.substring(8);
        String mes = data.substring(5, 7);
        String ano = data.substring(0, 4);
        String datafunc = dia + "/" + mes + "/" + ano;

        return datafunc;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCad_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCad_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCad_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCad_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCad_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPaginaInicial;
    private javax.swing.JButton btnPesquisaId;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField ftfCelular;
    private javax.swing.JFormattedTextField ftfCep;
    private javax.swing.JFormattedTextField ftfCpf;
    private javax.swing.JFormattedTextField ftfCrn;
    private javax.swing.JFormattedTextField ftfDataNasc;
    private javax.swing.JFormattedTextField ftfRg;
    private javax.swing.JFormattedTextField ftfTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMensagen;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtConsId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables

    private boolean emptyFields() {

        boolean empty = true;

        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo Nome precisa ser preenchido.");

        } else if (txtSobrenome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo Sobrenome precisa ser preenchido.");

        } else if (ftfDataNasc.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo Data de Nascimento precisa ser preenchido.");

        } else if (ftfRg.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo RG  precisa ser preenchido.");

        } else if (ftfCpf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo CPF precisa ser preenchido.");

        } else if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo Email precisa ser preenchido.");

        } else if (ftfCelular.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo Celular precisa ser preenchido.");

        } else if (ftfCrn.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo CRN precisa ser preenchido.");

        } else if (txtRua.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo Rua precisa ser preenchido.");

        } else if (txtNumero.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo Número precisa ser preenchido.");

        } else if (ftfCep.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo CEP precisa ser preenchido.");

        } else if (txtBairro.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo Bairro precisa ser preenchido.");

        } else if (txtCidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo Cidade precisa ser preenchido.");

        } else if (txtEstado.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Campo Estado precisa ser preenchido.");

        } else {

            empty = false;
        }

        return empty;
    }

    private boolean strValidacao() {

        boolean validacao = true;

        String strTeste = txtNome.getText();
        boolean palavra = strTeste.matches("[a-zA-Z ]*");
        String strTeste1 = txtSobrenome.getText();
        boolean palavra1 = strTeste1.matches("[a-zA-Z ]*");
        String strTeste2 = ftfDataNasc.getText();
        boolean palavra2 = strTeste2.matches("[0-9]{2}[/][0-9]{2}[/][0-9]{4}");
        String strTeste3 = ftfRg.getText();
        boolean palavra3 = strTeste3.matches("[0-9]{2}[.][0-9]{3}[.][0-9]{3}[-][0-9]{1}");
        String strTeste4 = ftfCpf.getText();
        boolean palavra4 = strTeste4.matches("[0-9]{3}[.][0-9]{3}[.][0-9]{3}[-][0-9]{2}");
        String strTeste5 = ftfTelefone.getText();
        boolean palavra5 = strTeste5.matches("[(][0-9]{2}[)][0-9]{4,}[-][0-9]{4}");
        String strTeste6 = txtEmail.getText();
        boolean palavra6 = strTeste6.matches("\\w+@\\w+\\.\\w{2,3}\\.\\w{2,3}");
        String strTeste7 = ftfCelular.getText();
        boolean palavra7 = strTeste7.matches("[(][0-9]{2}[)][0-9]{4,}[-][0-9]{4}");
        String strTeste8 = txtRua.getText();
        boolean palavra8 = strTeste8.matches("[a-zA-Z ]*");
        String strTeste9 = ftfCep.getText();
        boolean palavra9 = strTeste9.matches("[0-9]{5}[-][0-9]{3}");
        String strTeste10 = txtBairro.getText();
        boolean palavra10 = strTeste10.matches("[a-zA-Z ]*");
        String strTeste11 = txtCidade.getText();
        boolean palavra11 = strTeste11.matches("(?i)[\\p{L} ]*");
        String strTeste12 = txtEstado.getText();
        boolean palavra12 = strTeste12.matches("[a-zA-Z ]*");
        String strTeste13 = txtComplemento.getText();
        boolean palavra13 = strTeste13.matches("[a-zA-Z ]*");

        if (palavra == false) {
            JOptionPane.showMessageDialog(null, "No campo Nome digite apenas letras.");

        } else if (palavra1 == false) {
            JOptionPane.showMessageDialog(null, "No campo Sobrenome digite apenas letras.");

        } else if (palavra2 == false) {
            JOptionPane.showMessageDialog(null, "Data deve ser digitada no formato dd/mm/aaaa");

        } else if (palavra3 == false) {
            JOptionPane.showMessageDialog(null, "RG deve ser digitado no formato xx.xxx.xxx-x");

        } else if (palavra4 == false) {
            JOptionPane.showMessageDialog(null, "CPF deve ser digitado no formato xxx.xxx.xxx-xx");

        } else if (palavra5 == false) {
            JOptionPane.showMessageDialog(null, "Telefone deve ser digitado no formato (xx)xxxxx-xxxx");

        } else if (palavra6 == false) {
            JOptionPane.showMessageDialog(null, "E-mail precisa ser no formato nome@dominio.com.br ");

        } else if (palavra7 == false) {
            JOptionPane.showMessageDialog(null, "Telefone deve ser digitado no formato (xx)xxxxx-xxxx");

        } else if (palavra8 == false) {
            JOptionPane.showMessageDialog(null, "No campo Rua digite apenas letras.");

        } else if (palavra9 == false) {
            JOptionPane.showMessageDialog(null, "CEP deve ser digitado no formaro xxxxx-xxx.");

        } else if (palavra10 == false) {
            JOptionPane.showMessageDialog(null, "No campo Bairro digite apenas letras.");

        } else if (palavra11 == false) {
            JOptionPane.showMessageDialog(null, "No campo Cidade digite apenas letras.");

        } else if (palavra12 == false) {
            JOptionPane.showMessageDialog(null, "No campo Estafo digite apenas letras.");

        } else if (palavra13 == false) {
            JOptionPane.showMessageDialog(null, "No campo Complemento digite apenas letras.");

        } else {
            validacao = false;

        }

        return validacao;
    }

}
